<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="6" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21585" started-at="2014-05-13T09:54:39Z" finished-at="2014-05-13T09:55:00Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21585" started-at="2014-05-13T09:54:39Z" finished-at="2014-05-13T09:55:00Z">
      <class name="it.jnrpe.test.JnrpeParamTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="setUp" is-config="true" duration-ms="202" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testBadCommand()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testBadCommand" duration-ms="60" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testBadCommand -->
        <test-method status="PASS" signature="testCommandNullPointerException()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testCommandNullPointerException" duration-ms="31" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCommandNullPointerException -->
        <test-method status="PASS" signature="testCommandReturnNull()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testCommandReturnNull" duration-ms="4" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCommandReturnNull -->
        <test-method status="PASS" signature="testNullProviders()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testNullProviders" duration-ms="4" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:39Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[Plugin repository cannot be null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: Plugin repository cannot be null
	at it.jnrpe.JNRPE.<init>(JNRPE.java:84)
	at it.jnrpe.test.JnrpeParamTest.testNullProviders(JnrpeParamTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNullProviders -->
        <test-method status="PASS" signature="testPortInUse()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testPortInUse" duration-ms="11838" started-at="2014-05-13T11:54:39Z" finished-at="2014-05-13T11:54:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPortInUse -->
        <test-method status="PASS" signature="testThrowRuntimeException()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="testThrowRuntimeException" duration-ms="6" started-at="2014-05-13T11:54:51Z" finished-at="2014-05-13T11:54:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testThrowRuntimeException -->
        <test-method status="PASS" signature="shutDown()[pri:0, instance:it.jnrpe.test.JnrpeParamTest@24cd6034]" name="shutDown" is-config="true" duration-ms="9410" started-at="2014-05-13T11:54:51Z" finished-at="2014-05-13T11:55:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- shutDown -->
      </class> <!-- it.jnrpe.test.JnrpeParamTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
